---
repository: robzwolf/hackathon-template-jeyll
include: ["index.html", "_events",]

# Homepage settings
splash_title: 'Hack the Sky'
splash_subtitle: 'Make skydiving better! ✈️'
homepage_banner_image: photos/skydiving-bg.png
display_ad: true



footer-description: "Hack the Sky is a demo hackathon created for the purpose of creating and designing a hackathon brand at MLH Local Hack Day: Build 2021."


# Links for the navbar
navs:
  -
    name: Home
    link: "/#top"
  -
    name: Events
    link: "/#future-events"
  -
    name: Sponsor us
    link: "/assets/pdf/sponsordeck.pdf"


# Social media links included on the splash page
socials:
  -
    icon: "facebook-white.svg"
    name: Facebook
    url: "https://facebook.com/robzwolf"
  -
    icon: "twitter.svg"
    name: Twitter
    url: "https://twitter.com/robzwolf"
  -
    icon: "github-mark.png"
    name: GitHub
    url: "https://github.com/robzwolf"

email: hello@hackthesky.com


collections:
  events:
    output: true
    permalink: /:slug


sass:
  style: compressed
  sass_dir: _sass
